@startuml classes_nordility
set namespaceSeparator none
class "<color:red>CommandExecutionError</color>" as nordility.client.CommandExecutionError {
}
class "CommandResult" as nordility.client.CommandResult {
  command : tuple[str, ...]
  group : str | None
  message : str
  returncode : int | None
  stderr : str
  stdout : str
}
class "<color:red>ConfigurationError</color>" as nordility.client.ConfigurationError {
}
class "NordVPNClient" as nordility.client.NordVPNClient {
  backend : str
  executable
  change(speed: str, group: str | None, wait_seconds: float | None) -> CommandResult
  connect(group: str | None, wait_seconds: float) -> CommandResult
  disconnect(wait_seconds: float) -> CommandResult
  list_groups(speed: str) -> tuple[str, ...]
  pick_group(speed: str) -> str
}
class "<color:red>NordilityError</color>" as nordility.client.NordilityError {
}
nordility.client.CommandExecutionError --|> nordility.client.NordilityError
nordility.client.ConfigurationError --|> nordility.client.NordilityError
@enduml
